Дано: $u_t = u_{xx} + t*sh(x)$

$u(x,0) = 0$, $u(0,t) = 2t$, $u(1,t) = 3t^2$

$(x,t) $ $\epsilon $ $[0, 1]\times[0,0.5]$

Найти: $u(0.5,0.5)$

In [1]:
import numpy as np

In [47]:
def lin_u(x,t):
    if t == 0:
        return 0
    if x == 0:
        return 2*t
    if x == 1:
        return 3*t*t
    return 0


In [57]:
def dop_func(x,t):
    return t* (np.exp(x) - np.exp(-x))/2

In [82]:
def get_prost(nx, x=1,t=0.5):
    h = x/nx
    nt = int(np.ceil(t/(h*h/2)))
    s = t/nt
       
    matr = np.zeros((nt,nx))
    
    hx = np.linspace(0, x, nx)
    
    ht = np.linspace(0, t, nt)
    
    for i in range(nt):
        for j in range(nx):
            matr[i,j] = lin_u(hx[j], ht[i])
    
    return [matr, hx,ht,nx,nt,s/(h*h)]

In [83]:
matr, hx,ht ,nx,nt,q= get_prost(5)
print(matr)

[[0.         0.         0.         0.         0.        ]
 [0.04166667 0.         0.         0.         0.00130208]
 [0.08333333 0.         0.         0.         0.00520833]
 [0.125      0.         0.         0.         0.01171875]
 [0.16666667 0.         0.         0.         0.02083333]
 [0.20833333 0.         0.         0.         0.03255208]
 [0.25       0.         0.         0.         0.046875  ]
 [0.29166667 0.         0.         0.         0.06380208]
 [0.33333333 0.         0.         0.         0.08333333]
 [0.375      0.         0.         0.         0.10546875]
 [0.41666667 0.         0.         0.         0.13020833]
 [0.45833333 0.         0.         0.         0.15755208]
 [0.5        0.         0.         0.         0.1875    ]
 [0.54166667 0.         0.         0.         0.22005208]
 [0.58333333 0.         0.         0.         0.25520833]
 [0.625      0.         0.         0.         0.29296875]
 [0.66666667 0.         0.         0.         0.33333333]
 [0.70833333 0

In [84]:
matr.shape

(25, 5)

In [81]:
q

0.4999999999999999